### PR TITLE
Create payment request page

### LINKED ISSUE #20: Treasury - Operations > Payments: Create Payment Request Page
Note: This ticket is related to https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19

# User Story
As an admin with create permissions, I want to create new payment requests so that other committee members with approve permissions can review and authorize outgoing payments from the treasury.

# Acceptance Criteria
 - The "Create Payment Request" page is accessible by clicking the "Create Payment Request" button on the "[Pending Requests](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/19)" page.
 - The page includes the following fields:
   - From Wallet: A dropdown menu displaying the DevDAO wallet address with the available balances (e.g. USDC and NEAR).
   - Choose Proposal: A dropdown menu to select a proposal from a list of existing proposals in the portal.
   - To Wallet (Recipient): A dropdown menu to select a recipient from a list of pre-approved recipients (from the Payment Recipients page) with :
   - KYC/KYB Verification: A checkbox to confirm that the recipient has complete KYC or KYB verification.
   - Test Transaction Confirmed: A checkbox to confirm that a test transaction has been successfully sent to the recipient's wallet address.
   - Information Message: Payment Recipients Tab links to Payment Recipients page. 
   - Total Amount: A text input field for entering the payment amount.
   - Currency: A dropdown menu to select the currency of the payment (e.g., NEAR, USDC).
   - Notes: A text area for adding any additional notes or details about the payment.
   - Cancel: A button to cancel the creation of the payment request. This will take the user back to the previous screen.
   - Submit: A button to submit the payment request.
 - The "Submit" button is disabled until all required fields are filled out correctly.
 - Upon submission, the payment request is added to the "Pending Requests" page and awaits approval. And the user is redirected to the Pending Requests page, where they see the new request.

# Attachments
Payment-Create-New

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
Resolves #20 
image

### CODE REVIEW

**Comment by Megha-Dev-19** [comment]
Note: for the tests I have created a separate ticket [here](https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/issues/31)

**Comment by Megha-Dev-19** [comment]
@race-of-sloths please, include my PR in the Race

**Comment by race-of-sloths** [comment]
@Megha-Dev-19 Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!


[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/Megha-Dev-19?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/Megha-Dev-19?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/Megha-Dev-19)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command
</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Megha-Dev-19)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by Megha-Dev-19** [comment]
@race-of-sloths pause

**Comment by race-of-sloths** [comment]
### ⏸️ Repository paused 
Scored PRs will be accepted after the merge. No further actions will be taken by the bot until you call `@race-of-sloths unpause` command to restart our service

**Comment by petersalomonsen** [comment]
@race-of-sloths score 13

**Review by petersalomonsen — APPROVED** [review]

**Pull request merged**
