### PR TITLE
Setup moderators and trustees dashboard

### PR DESCRIPTION
**Pull request by Megha-Dev-19**
- add automatic watch of the `src` folder to trigger build when there are changes
- fix replacements for common include files ( only the first `export` was removed )
- support both `jsx` and `tsx` in the same project

### CODE REVIEW

**Comment by petersalomonsen** [comment]
the line with the `build` script in package.json does not seem to copy `.jsx` files when combining `typescript` and `jsx`  in transforms.

a quick fix is to have two `sucrase` commands like this: 

```
  "build": "npm run fmt && rimraf .bos/transpiled && mkdir -p .bos/transpiled/src && sucrase ./src -d .bos/transpiled/src/neardevhub-trustees --transforms jsx --jsx-runtime preserve --disable-es-transforms --out-extension jsx && sucrase ./src -d .bos/transpiled/src/neardevhub-trustees --transforms typescript --jsx-runtime preserve --disable-es-transforms --out-extension jsx && node ./build.js",
```

**Comment by petersalomonsen** [comment]
@Megha-Dev-19 see my latest commit that makes sure that both transpiled tsx and jsx files are copied. It also fixes so that every line starting with `export` in common.tsx is adjusted to not contain the `export` statement.

**Comment by petersalomonsen** [comment]
@Megha-Dev-19 Check out the watcher in the latest commit. You can now run `npm run build:watch` to automatically build when there are changes in the src folder.

**Comment by Megha-Dev-19** [comment]
@petersalomonsen thank you so much, everything works as expected

**Comment by Megha-Dev-19** [comment]
Closing, since we will integrate bos-workspace

**Pull request closed without merging**
