### PR TITLE
Update web4 deploy to `treasury-testing.near`

### PR DESCRIPTION
**Pull request by Megha-Dev-19**

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@race-of-sloths include

**Review by petersalomonsen — APPROVED** [review]
Should check the tests though.

**Comment by race-of-sloths** [comment]
### ⏸️ This repository is on pause
@petersalomonsen please reach out to the maintainer to unpause this repo with `@race-of-sloths unpause` command

**Comment by petersalomonsen** [comment]
@race-of-sloths include

**Comment by petersalomonsen** [comment]
@race-of-sloths score 3

**Pull request merged**
