### PR TITLE
fix web4 contract after rust upgrade

### LINKED ISSUE #81: Web4 contract fails on prepare after Rust 1.82
I investigated Treasury dashboard web4 failing in near-workspaces-rs as we can see from the latest test runs.

Image

Our web4 contract for treasury suddenly fails after deployment when calling the web4_get view method ( https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/actions/runs/11389758815/job/31690065639?pr=76 )

Custom { kind: Rpc(QueryFailure), error: ServerError(HandlerError(ContractExecutionError { vm_error: ""wasm execution failed with error: CompilationError(PrepareError(Deserialization))"", block_height: 28, block_hash: JChV9MQzjK7cJu7bMh2n5rp5ovvjrZihTh1jkiUwiuPN })) } }

There are no changes on our side, so it has to be in the dependencies or network.

It fails both in the near-workspaces-rs and on testnet. 

I notice that existing web4 contracts are running fine, but when deploying a new build now then it fails.

It all worked until yesterday ( here is the latest successful test with near-workspaces-rs: https://github.com/NEAR-DevHub/neardevhub-treasury-dashboard/actions/runs/11372008429/job/31635347678 )

-----

After reaching out, got the feedback that the reason is support for new Wasm features in Rust 1.82, and that cargo-near-build has a fix ( utilizing wasm-opt ), I noticed that near-workspaces-rs does still not have a new release using the latest cargo-near-build. Will wait for a new release of near-workspaces-rs.

As soon as a new release of near-workspaces-rs is ready, it has to linked in here

### PR DESCRIPTION
**Pull request by petersalomonsen**
- upgrade web4 contract to use near-workspaces-rs 0.14.1 which has the fix to handle the Wasm upgrade in Rust 1.82.0
- Adjust codespace definition to use feature packs for cargo-near and near-cli instead of installing these in the post-install bash script
- Use `#[derive(Default)]` directive in web4 contract instead of `impl` block
- Fix compiler warnings about unused variables
- remove bos-loader from codespace post-install as this is not in use
- upgrade web4 contract to use near-sdk-rs 5.5

fixes #81

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
@petersalomonsen Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Congratulatory messages are spent out! Your results have exceeded our imagination!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://race-of-sloths.com/images/bot-banner-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://race-of-sloths.com/images/bot-banner-light.svg">
    Shows inviting banner with latest news.
</picture>](https://race-of-sloths.com/latest-news)

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&pr=NEAR-DevHub/neardevhub-treasury-dashboard/82&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/petersalomonsen?type=bot&pr=NEAR-DevHub/neardevhub-treasury-dashboard/82&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/petersalomonsen)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/petersalomonsen)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Review by Tguntenaar — APPROVED** [review]
Looks good!

**Comment by Tguntenaar** [comment]
@race-of-sloths score 3

**Pull request merged**
